# Generated by Django 5.2.17 on 2026-09-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='compareceu',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
