# Generated by Django 5.2.17 on 2026-09-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_visita_compareceu'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='cancelada_por_visitante',
            field=models.BooleanField(default=False),
        ),
    ]
