# Generated by Django 5.2.17 on 2026-09-07 22:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0003_visita_cancelada_por_visitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='token',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
    ]
